# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5bbd49c176aa926e31e24c0672efe9e379043a9d8983c46c19693a7dd9bccebf7daf95404377d7c096dcdaa68c789766b33f711e01665c52fba6daab5738f34

test:
  secret_key_base: 407ca7a356efd8fcf2b8a7cbff120d04bdcf9a05023aac80a5b4fa18a4e179bc665b24f29fe5ba9f70052c39552a047b01841d94b0b6f311632527dae19ea530

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
